Repository Anamaya1729/Machine-Learning-Basics, pull requests merged in 2022-10, with the labels that each got.

#1 added CNN model ipynb in ML_advanced (cnn_handwrittern_digits_recognition)
  ML_advance/cnn_handwrittern_digits_recognition/cnn_handwrittern_digits_recognition.ipynb
Labels: hacktoberfest-accepted

#6 Added Air Pollution Regression
  ML_simple_project/air_pollution_regression/Air Pollution.ipynb
  ML_simple_project/air_pollution_regression/README.md
  ML_simple_project/air_pollution_regression/Sample_Submission.csv
  ML_simple_project/air_pollution_regression/Test.csv
  ML_simple_project/air_pollution_regression/Train.csv
Labels: hacktoberfest-accepted

#8 Heart Failure Prediction
  ML_simple_project/Heart_failure_Prediction/Heart_Failure_Prediction.ipynb
  ML_simple_project/Heart_failure_Prediction/README.md
  ML_simple_project/Heart_failure_Prediction/heart_failure_clinical_records_dataset.csv
Labels: hacktoberfest

#11 Implement customer churn prediction model
  ML_simple_project/customer_churn_prediction/README.md
  ML_simple_project/customer_churn_prediction/customer_churn_prediction.ipynb
Labels: hacktoberfest

#10 MNIST_HandWrittenDigits_Dense_layer
  ML_advance/cnn_handwritten_digits_recognition_project_2/1.png
  ML_advance/cnn_handwritten_digits_recognition_project_2/HandWrittenDigits.ipynb
  ML_advance/cnn_handwritten_digits_recognition_project_2/HandWrittenDigits.pdf
  ML_advance/cnn_handwritten_digits_recognition_project_2/README.md
  ML_advance/cnn_handwritten_digits_recognition_project_2/Screenshot from 2022-09-06 10-41-08.jpg
  ML_advance/cnn_handwritten_digits_recognition_project_2/Screenshot from 2022-09-06 10-41-08.jpg.npy
  ML_advance/cnn_handwritten_digits_recognition_project_2/Screenshot from 2022-09-06 10-41-08.npy
  ML_advance/cnn_handwritten_digits_recognition_project_2/Screenshot from 2022-09-07 22-07-11.jpg
  ML_advance/cnn_handwritten_digits_recognition_project_2/Screenshot from 2022-09-07 22-07-11.npy
  ML_advance/cnn_handwritten_digits_recognition_project_2/Screenshot from 2022-09-07 22-11-11.jpg
  ML_advance/cnn_handwritten_digits_recognition_project_2/Screenshot from 2022-09-07 22-11-11.npy
  ML_advance/cnn_handwritten_digits_recognition_project_2/Screenshot from 2022-09-07 22-13-05.jpg
  ML_advance/cnn_handwritten_digits_recognition_project_2/Screenshot from 2022-09-07 22-13-05.npy
  ML_advance/cnn_handwritten_digits_recognition_project_2/Screenshot from 2022-09-07 22-18-55.jpg
  ML_advance/cnn_handwritten_digits_recognition_project_2/Screenshot from 2022-09-07 22-18-55.npy
  ML_advance/cnn_handwritten_digits_recognition_project_2/Screenshot from 2022-09-07 22-26-08.jpg
  ML_advance/cnn_handwritten_digits_recognition_project_2/Screenshot from 2022-09-07 22-26-08.npy
  ML_advance/cnn_handwritten_digits_recognition_project_2/Screenshot from 2022-09-08 00-16-49.jpg
  ML_advance/cnn_handwritten_digits_recognition_project_2/Screenshot from 2022-09-08 00-16-49.npy
  ML_advance/cnn_handwritten_digits_recognition_project_2/Screenshot from 2022-09-08 01-02-52.jpg
  ML_advance/cnn_handwritten_digits_recognition_project_2/Screenshot from 2022-09-08 01-02-52.npy
  ML_advance/cnn_handwritten_digits_recognition_project_2/Screenshot from 2022-09-08 01-06-40.jpg
  ML_advance/cnn_handwritten_digits_recognition_project_2/Screenshot from 2022-09-08 01-06-40.npy
  ML_advance/cnn_handwritten_digits_recognition_project_2/Screenshot from 2022-09-20 16-58-53.png
  ML_advance/cnn_handwritten_digits_recognition_project_2/Screenshot from 2022-09-20 16-58.npy
  ML_advance/cnn_handwritten_digits_recognition_project_2/Screenshot from 2022-09-20 16-58.png
  ML_advance/cnn_handwritten_digits_recognition_project_2/Screenshot from 2022-09-27 21-19.npy
  ML_advance/cnn_handwritten_digits_recognition_project_2/Screenshot from 2022-09-27 21-19.png
  ML_advance/cnn_handwritten_digits_recognition_project_2/i1.jpg
  ML_advance/cnn_handwritten_digits_recognition_project_2/resized__image.jpg
  ML_advance/cnn_handwritten_digits_recognition_project_2/sized__image.jpg
Labels: hacktoberfest-accepted, hacktoberfest

#18 E-Mail Classification Project
  ML_simple_project/e-mail_classification/Dataset/email.csv
  ML_simple_project/e-mail_classification/Model/E-Mail Classification.ipynb
  ML_simple_project/e-mail_classification/Model/E-MailClassification.pkl
  ML_simple_project/e-mail_classification/README.md
Labels: hacktoberfest-accepted
